# Generated by Django 4.2.2 on 2023-06-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdash', '0003_rename_contact_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pics', models.ImageField(blank=True, default='profile2.png', null=True, upload_to='')),
                ('name', models.CharField(blank=True, max_length=155, null=True)),
                ('title', models.TextField(max_length=5000)),
                ('date', models.DateTimeField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=155, null=True)),
                ('department', models.CharField(blank=True, max_length=155, null=True)),
                ('theme', models.TextField(max_length=5000)),
                ('date', models.DateTimeField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendedbible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse1', models.CharField(blank=True, max_length=155, null=True)),
                ('verse2', models.CharField(blank=True, max_length=155, null=True)),
                ('verse3', models.TextField(blank=True, max_length=155, null=True)),
                ('verse4', models.TextField(blank=True, max_length=5000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seedofwin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=155, null=True)),
                ('bible_verse', models.CharField(blank=True, max_length=155, null=True)),
                ('power_capsule', models.TextField(blank=True, max_length=155, null=True)),
                ('content', models.TextField(blank=True, max_length=5000, null=True)),
                ('bible_reading', models.TextField(blank=True, max_length=155, null=True)),
                ('prayer_bullet', models.TextField(blank=True, max_length=5000, null=True)),
                ('date', models.DateTimeField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
