# Generated by Django 4.2.2 on 2023-06-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdash', '0004_event_program_recommendedbible_seedofwin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=155, null=True)),
                ('title', models.CharField(blank=True, max_length=155, null=True)),
                ('content', models.TextField(blank=True, max_length=155, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
