# Generated by Django 4.2.2 on 2023-06-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdash', '0005_prayer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendedbible',
            old_name='verse4',
            new_name='versefour',
        ),
        migrations.RenameField(
            model_name='recommendedbible',
            old_name='verse1',
            new_name='verseone',
        ),
        migrations.RenameField(
            model_name='recommendedbible',
            old_name='verse3',
            new_name='versethree',
        ),
        migrations.RenameField(
            model_name='recommendedbible',
            old_name='verse2',
            new_name='versetwo',
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='program',
            name='department',
            field=models.CharField(blank=True, choices=[('Hebrew Women', 'Hebrew Women'), ('Excellent Men', 'Excellent Men'), ('Great Youth', 'Great Youth'), ('Eminence Children', 'Eminence Children')], max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='seedofwin',
            name='bible_reading',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='seedofwin',
            name='power_capsule',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='seedofwin',
            name='prayer_bullet',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
