# Generated by Django 4.2.2 on 2023-06-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdash', '0006_rename_verse4_recommendedbible_versefour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recommendedbible',
            name='versefour',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='recommendedbible',
            name='versethree',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
