# Generated by Django 4.2.2 on 2023-06-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdash', '0007_alter_event_date_alter_recommendedbible_versefour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_pic',
            field=models.ImageField(default='profile2.png', null=True, upload_to=''),
        ),
    ]
