# Generated by Django 4.2.2 on 2023-06-19 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdash', '0008_alter_member_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='pics',
        ),
    ]
