# Generated by Django 4.2.2 on 2023-06-18 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_newuser_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='profile_pic',
        ),
    ]
